/*
 * Entrywan API
 *
 * Manage Entrywan resources programmatically using the API.  All API requests are authenticated using [IAM tokens](https://entrywan.com/docs#iam).  Tokens can be generated and retrieved from the [portal](https://portal.entrywan.com).  The portal itself is an API client that uses an unrestricted token to access resources for an account.  This documentation is generated using an OpenAPI 3.1.0 [specification](https://spec.openapis.org/oas/latest.html).  More information about OpenAPI can be found on its [site](https://openapis.org).  The current version of [Entrywan's API spec](https://entrywan.com/openapi.yaml) is also available for inspection.  On the left of this page are links to the <i>Endpoints</i> grouped by tag and <i>Schemas</i> the API exposes.  <i>Endpoints</i> are URLs that can be accessed with any HTTP client or device. <i>Schemas</i> are machine-readable data models that represent resources.  To learn more, have a look at the [documentation](https://entrywan.com/docs).  If you have any questions, contact [support](mailto:support@entrywan.com) or your account representative.
 *
 * The version of the OpenAPI document: v1beta
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Instance {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Instance state
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// Instance hostname
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    /// Instance account owner
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<uuid::Uuid>,
    #[serde(rename = "ip4", skip_serializing_if = "Option::is_none")]
    pub ip4: Option<String>,
    /// Instance datacenter location
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Location>,
    /// Instance CPU cores
    #[serde(rename = "cpus", skip_serializing_if = "Option::is_none")]
    pub cpus: Option<crate::models::Int>,
    /// Instance memory in gigabytes (GB)
    #[serde(rename = "ram", skip_serializing_if = "Option::is_none")]
    pub ram: Option<crate::models::Int>,
    /// Instance hard drive size in gigabytes (GB)
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<crate::models::Int>,
}

impl Instance {
    pub fn new() -> Instance {
        Instance {
            id: None,
            state: None,
            hostname: None,
            account: None,
            ip4: None,
            location: None,
            cpus: None,
            ram: None,
            disk: None,
        }
    }
}

/// Instance state
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "creating")]
    Creating,
    #[serde(rename = "deleting")]
    Deleting,
}

impl Default for State {
    fn default() -> State {
        Self::Running
    }
}
/// Instance datacenter location
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Location {
    #[serde(rename = "us1")]
    Us1,
}

impl Default for Location {
    fn default() -> Location {
        Self::Us1
    }
}

